
server:
  port: 8999

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zjs
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  type-aliases-package: cn.zjs.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
